---
- hosts: all
  vars:
    compose_file: "{{ compose_file }}"
    project_folder: pd_project

  tasks:
    - name: create project directory
      shell: cd .. && mkdir "{{ project_folder }}" -p && cd "{{ project_folder }}"

    - name: write variable to file
      shell: echo "{{ compose_file }}" > touch newfile.txt
