---
- hosts: all
  vars:
    compose_file: "{{ compose_file }}"
    project_folder: pd_project

  tasks:
    - name: create project directory
      shell: mkdir -p "{{ project_folder }}"

    - name: write variable to file
      shell: echo "{{ compose_file }}" > "{{ project_folder }}/newfile.txt"
